# Generated by Django 5.0.6 on 2024-06-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userauth',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
