# Generated by Django 5.0.6 on 2024-06-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='salt',
        ),
    ]
