# Generated by Django 5.0.6 on 2024-06-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_userauth_options_userauth_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='username',
        ),
    ]
