# Generated by Django 5.0.6 on 2024-06-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_cliente_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
