# Generated by Django 5.0.6 on 2024-06-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
