# Generated by Django 5.0.6 on 2024-06-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_carrito_delete_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_Oferta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
