# Generated by Django 5.0.6 on 2024-06-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_listadeseos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
